
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CANOPENSHELLMASTEROD_H
#define CANOPENSHELLMASTEROD_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 CANOpenShellMasterOD_valueRangeTest (UNS8 typeValue, void * value);
const indextable * CANOpenShellMasterOD_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data CANOpenShellMasterOD_Data;
extern UNS8 NodeId;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 BitRate;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS32 Port_Configuration;		/* Mapped at index 0x2100, subindex 0x00*/
extern INTEGER32 Poll_List_poll_list_entry_1;		/* Mapped at index 0x2200, subindex 0x01 */
extern INTEGER32 Poll_List_poll_list_entry_2;		/* Mapped at index 0x2200, subindex 0x02 */
extern INTEGER32 Poll_List_poll_list_entry_3;		/* Mapped at index 0x2200, subindex 0x03 */
extern INTEGER32 Poll_List_poll_list_entry_4;		/* Mapped at index 0x2200, subindex 0x04 */
extern INTEGER32 User_Variable_User_Array_Index;		/* Mapped at index 0x2201, subindex 0x01 */
extern INTEGER32 User_Variable_User_Array_Value;		/* Mapped at index 0x2201, subindex 0x02 */
extern UNS32 Set_Actual_Position;		/* Mapped at index 0x2202, subindex 0x00*/
extern UNS16 Bus_Voltage;		/* Mapped at index 0x2300, subindex 0x00*/
extern UNS16 RMS_Current;		/* Mapped at index 0x2301, subindex 0x00*/
extern UNS8 Internal_Temperature;		/* Mapped at index 0x2302, subindex 0x00*/
extern UNS32 Internal_Clock;		/* Mapped at index 0x2303, subindex 0x00*/
extern UNS16 Motor_Status;		/* Mapped at index 0x2304, subindex 0x00*/
extern UNS16 Motor_Control;		/* Mapped at index 0x2305, subindex 0x00*/
extern INTEGER16 Motor_Subroutine_Index;		/* Mapped at index 0x2306, subindex 0x00*/
extern UNS16 Sample_Period;		/* Mapped at index 0x2307, subindex 0x00*/
extern UNS16 Interpolation_Mode_Status;		/* Mapped at index 0x2400, subindex 0x00*/
extern INTEGER8 InterpolationTimePeriod[6];		/* Mapped at index 0x2500, subindex 0x01 - 0x06 */
extern UNS8 InterpolationTimeValue[6];		/* Mapped at index 0x2501, subindex 0x01 - 0x06 */
extern INTEGER32 InterpolationData[6];		/* Mapped at index 0x2502, subindex 0x01 - 0x06 */
extern UNS16 Controlword;		/* Mapped at index 0x6040, subindex 0x00*/
extern UNS16 Statusword;		/* Mapped at index 0x6041, subindex 0x00*/
extern INTEGER16 Quick_Stop_Option_Code;		/* Mapped at index 0x605A, subindex 0x00*/
extern INTEGER16 Halt_Option_Code;		/* Mapped at index 0x605D, subindex 0x00*/
extern INTEGER8 Modes_of_operation;		/* Mapped at index 0x6060, subindex 0x00*/
extern INTEGER8 Modes_of_operation_display;		/* Mapped at index 0x6061, subindex 0x00*/
extern INTEGER32 Position_Actual_Value;		/* Mapped at index 0x6063, subindex 0x00*/
extern UNS32 Maximal_following_error;		/* Mapped at index 0x6065, subindex 0x00*/
extern INTEGER32 Velocity_actual_value;		/* Mapped at index 0x606C, subindex 0x00*/
extern INTEGER16 Target_Torque;		/* Mapped at index 0x6071, subindex 0x00*/
extern UNS16 Max_Torque;		/* Mapped at index 0x6072, subindex 0x00*/
extern UNS16 Max_Current;		/* Mapped at index 0x6073, subindex 0x00*/
extern INTEGER32 Target_position;		/* Mapped at index 0x607A, subindex 0x00*/
extern INTEGER32 Home_offset;		/* Mapped at index 0x607C, subindex 0x00*/
extern INTEGER32 Software_position_limit_Minimal_position_limit;		/* Mapped at index 0x607D, subindex 0x01 */
extern INTEGER32 Software_position_limit_Maximal_position_limit;		/* Mapped at index 0x607D, subindex 0x02 */
extern UNS8 Polarity;		/* Mapped at index 0x607E, subindex 0x00*/
extern UNS32 Maximal_profile_velocity;		/* Mapped at index 0x607F, subindex 0x00*/
extern UNS32 Profile_velocity;		/* Mapped at index 0x6081, subindex 0x00*/
extern UNS32 Profile_acceleration;		/* Mapped at index 0x6083, subindex 0x00*/
extern UNS32 Quick_stop_deceleration;		/* Mapped at index 0x6085, subindex 0x00*/
extern UNS32 Position_Encoder_Resolution_Encoder_Increments;		/* Mapped at index 0x608F, subindex 0x01 */
extern UNS32 Position_Encoder_Resolution_Motor_Revolutions;		/* Mapped at index 0x608F, subindex 0x02 */
extern INTEGER8 Homing_method;		/* Mapped at index 0x6098, subindex 0x00*/
extern UNS32 Homing_speeds_Speed_for_switch_search;		/* Mapped at index 0x6099, subindex 0x01 */
extern UNS32 Homing_speeds_Speed_for_zero_search;		/* Mapped at index 0x6099, subindex 0x02 */
extern UNS32 Homing_acceleration;		/* Mapped at index 0x609A, subindex 0x00*/
extern INTEGER32 Following_Error_Actual_Value;		/* Mapped at index 0x60F4, subindex 0x00*/
extern UNS16 Position_Control_Parameter_Set_KP_Proportional_Gain;		/* Mapped at index 0x60FB, subindex 0x01 */
extern UNS16 Position_Control_Parameter_Set_KI_Integral_Gain;		/* Mapped at index 0x60FB, subindex 0x02 */
extern UNS16 Position_Control_Parameter_Set_KL_Integral_Limit;		/* Mapped at index 0x60FB, subindex 0x03 */
extern UNS16 Position_Control_Parameter_Set_KD_Derivative_Gain;		/* Mapped at index 0x60FB, subindex 0x04 */
extern UNS8 Position_Control_Parameter_Set_KS_Derivative_Damping_Sample_Rate;		/* Mapped at index 0x60FB, subindex 0x05 */
extern UNS16 Position_Control_Parameter_Set_KV_Velocity_Feedforward_Gain;		/* Mapped at index 0x60FB, subindex 0x06 */
extern UNS16 Position_Control_Parameter_Set_KA_Acceleration_Feedforward_Gain;		/* Mapped at index 0x60FB, subindex 0x07 */
extern INTEGER32 Position_Control_Parameter_Set_KG_Gravitational_Offset;		/* Mapped at index 0x60FB, subindex 0x08 */
extern UNS32 Digital_Inputs;		/* Mapped at index 0x60FD, subindex 0x00*/
extern UNS32 Digital_Outputs_Physical_Outputs;		/* Mapped at index 0x60FE, subindex 0x01 */
extern INTEGER32 Target_velocity;		/* Mapped at index 0x60FF, subindex 0x00*/
extern INTEGER16 Read_Analog_Input_16_Bit_16_Bit_analog_Input_1;		/* Mapped at index 0x6401, subindex 0x01 */
extern INTEGER16 Read_Analog_Input_16_Bit_16_Bit_analog_Input_2;		/* Mapped at index 0x6401, subindex 0x02 */
extern INTEGER16 Read_Analog_Input_16_Bit_16_Bit_analog_Input_3;		/* Mapped at index 0x6401, subindex 0x03 */
extern INTEGER16 Read_Analog_Input_16_Bit_16_Bit_analog_Input_4;		/* Mapped at index 0x6401, subindex 0x04 */
extern INTEGER16 Read_Analog_Input_16_Bit_16_Bit_analog_Input_5;		/* Mapped at index 0x6401, subindex 0x05 */
extern INTEGER16 Read_Analog_Input_16_Bit_16_Bit_analog_Input_6;		/* Mapped at index 0x6401, subindex 0x06 */
extern INTEGER16 Read_Analog_Input_16_Bit_16_Bit_analog_Input_7;		/* Mapped at index 0x6401, subindex 0x07 */
extern UNS16 Motor_type;		/* Mapped at index 0x6402, subindex 0x00*/
extern UNS8 Motor_Catalogue_Number[10];		/* Mapped at index 0x6403, subindex 0x00*/
extern UNS8 Motor_Manufacturer[21];		/* Mapped at index 0x6404, subindex 0x00*/
extern UNS8 Http_Motor_Catalog_Address[17];		/* Mapped at index 0x6405, subindex 0x00*/
extern UNS32 Supported_drive_modes;		/* Mapped at index 0x6502, subindex 0x00*/
extern UNS8 Drive_Catalog_Number[10];		/* Mapped at index 0x6503, subindex 0x00*/
extern UNS8 Drive_Manufacturer[21];		/* Mapped at index 0x6504, subindex 0x00*/
extern UNS8 Http_Drive_Catalog_Address[17];		/* Mapped at index 0x6505, subindex 0x00*/
extern UNS16 Drive_Data_RMS_time_before_shutdown;		/* Mapped at index 0x6510, subindex 0x01 */
extern UNS8 Drive_Data_Internal_Temperature_Limit;		/* Mapped at index 0x6510, subindex 0x02 */
extern UNS32 Single_Device_Type;		/* Mapped at index 0x67FF, subindex 0x00*/

#endif // CANOPENSHELLMASTEROD_H
